### ISSUE TITLE
Знайти зображення коледжу в інтернеті

### ISSUE THREAD

**Issue by namori443** [namori443/test_proje-t#1]
Знайти фотографію корпусів коледжу в мережі інтернет.
![zceuktfz2um](https://cloud.githubusercontent.com/assets/23519218/20382253/c7e089da-acb3-11e6-983b-2fbf2340d4a5.jpg)

**Comment by kubennn98** [comment]
Я закінчив проект!
https://camo.githubusercontent.com/27f2a7cd9e3381f1a6697242b1f2fb664699b847/687474703a2f2f7777772e6e72706b2e6c7669762e75612f696d616765732f6f746865722f686f6c5f6b6f727075735f736d616c6c2e6a7067
